cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('index/<int:id>', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('delete/', views.delete, name='delete'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
]

mikeshoes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('cart/', include('cart.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


cart/models.py
from django.db import models
from item.models import Item
from django.contrib.auth.models import User
from item.models import Item


class Category(models.Model):
    name = models.CharField(max_length=255)
    
    # To change the model name is the admin to 'Categories' instead of 'Catergoys'.
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name


class CartItem(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='cart', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name

cart/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators  import login_required
from item.models import Item
from .models import CartItem

@login_required
def index(request, id):
    item = get_object_or_404(Item, id=id)
    cart = CartItem.objects.all()
    item_already_in_cart = False
    for x in cart:
        if item.description == x.description:
            item_already_in_cart = True
            print('Item already included')
            break
    if not item_already_in_cart:
        my_cart = CartItem.objects.create(
            
            name= item.name,
            description= item.description,
            price = item.price,
            image = item.image,
            is_sold = item.is_sold,
            created_by = request.user,
            created_at = item.created_at
        )
        my_cart.save()
        cart = CartItem.objects.filter(created_by=request.user)
    return render(request, 'cart/index.html',{
        'my_cart': cart,
    })

@login_required
def cart(request):
    cart = CartItem.objects.filter(created_by=request.user)
    return render(request,'cart/index.html',{
        'my_cart': cart,
    })

def detail(request, pk):
    item = get_object_or_404(CartItem, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]
    
    return render(request, 'cart/detail.html', {
        'item':item,
        'related_items':related_items,
    })

def delete(request):
    cart = CartItem.objects.all()
    cart.delete()
    return render(request,'cart/index.html',{
        'my_cart': cart,
    })

cart/templates/cart/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock title %}

{% block content %}
load
    <div class='grid grid-cols-5 gap-6'>
        <div class='col-span-3 flex justify-center'>
            <img src="{{ item.image.url }}" class='rounded-xl'>
        </div>

        <div class='col-span-2 p-6 bg-gray-100 rounded-xl'>
            <h1 class='mb-6 text-3xl'>{{ item.name }}</h1>
            <p class='text-gray-500'><strong>Price: </strong>{{ item.price }}</p>
            <p class='text-gray-500'><strong>Seller: </strong>{{ item.created_by.username }}</p>

            {% if item.description %}
                <p class='text-gray-700'>
                    <strong class='text-gray-500'>Description:</strong><br>
                    {{ item.description }}
                </p>
            {% endif %}
            {% if request.user == item.created_by %}
                <div class='mt-6 p-6 bg-white rounded-xl'>
                    <p>This is your item!</p>
                    <a href="{% url 'item:edit' item.id %}" class='inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl'>Edit</a>
                    <a href="{% url 'item:delete' item.id %}" class='inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl'>Delete</a>
                </div>
            {% else %}
            <a href="wa.link/rmhcsd" target="_blank" class='inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700'><img src="{% static 'whatsapp.png' %}">Contact Seller</a>
            <a href="#" class='inline-block mt-6 px-6 py-3 text-lg font-semibold bg-yellow-500 text-white rounded-xl hover:bg-yellow-700'>Remove from cart</a>
            {% endif %}
            
            
        </div>
    </div>

    <div class = 'mt-6 px-6 py-12 bg-gray-100 rounded-xl'>
        <h2 class='mb-12 text-2xl text-center'>Related items</h2>

        <div class='grid grid-cols-3 gap-10'>
            {% for item in related_items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class='rounded-t-xl'>
                        </div>

                        <div class='p-6 bg-gray rounded-b-xl'>
                            <h2 class='text-2xl'>{{ item.name }}</h2>
                            <p class='text-gray-500'>Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

cart/templates/cart/index.html
{% extends 'core/base.html' %}

{% block title %}My Cart Items{% endblock %}
{% block content %}
<h3>My Cart Items</h3>
<a href="{% url 'cart:delete' %}" class='py-3 px-5 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white'>Clear cart</a>
<div class='grid grid-cols-4 gap-4'>
    {% for item in my_cart %}
        <div>
            <a href="{% url 'item:detail' item.id %}">
                <div>
                    <img src="{{ item.image.url }}" class='rounded-t-xl'>
                </div>

                <div class='p-6 bg-gray rounded-b-xl'>
                    <h2 class='text-2xl'>{{ item.name }}</h2>
                    <p class='text-gray-500'>Price: {{ item.price }}</p>
                    
                </div>
            </a>
        </div>
    {% endfor %}
</div>

{% endblock %}