cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('index/<int:id>', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('delete/', views.delete, name='delete'),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
]

mikeshoes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('cart/', include('cart.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'Your Email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignUpForm
from django.contrib.auth import logout, login

def index(request):
    items = Item.objects.filter(is_sold=False) # Getting the all newest unsold products
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        
        if form.is_valid():
            form.save()
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    
    return render(request, 'core/signup.html', {
        'form': form
    })


def logoutuser(request):
    logout(request)
    return render(request, 'core/index.html')

core/templates/core/base.html
{% load static %}
{% load static tailwind_tags %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% tailwind_css %}

    
    <!--<link rel="stylesheet" href="{% static 'css\syles.css' %}">-->
    <title>Mike's Shoes</title>

  
  </head>
  <body>
    
    <nav class='py-6 px-6 flex justify-between items-center border-b border-gray-200 '>
        
        <a href='/' class='text-x font-semibold'>Mike's Shoes</a>
        <div class='space-x-6 nav1 flex'>
            <div><a href="{% url 'item:items' %}" class='text-lg font-semibold hover:text-gray-500'>Browse</a></div>
            {% if request.user.is_authenticated %}
            {% if user.is_authenticated and user.is_staff %}
                <span><a href="{% url 'item:new' %}" class='text-lg font-semibold hover:text-lime-900'>New</a></span>
            {% endif %}

                <span><a href="{% url 'cart:cart' %}" class='px-6 py-3 text-lg font-semibold bg-violet-700 text-white rounded-xl hover:bg-lime-700'>Cart</a></span>
                <span><a href="{% url 'core:logout' %}" class='px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700'>Logout</a></span>

            {% else %}
                <span><a href="{% url 'core:signup' %}" class='px-6 py-3 text-lg font-semibold bg-violet-700 text-white rounded-xl hover:bg-teal-700'>Sign Up</a></span>
                <span><a href="{% url 'core:login' %}" class='px-6 py-3 text-lg font-semibold bg-violet-700 text-white rounded-xl hover:bg-gray-700'>Log in</a></span>
            {% endif %}
            
        </div>


        
    </nav>

    <div class='px-6 py-6 item-flex'>
        {% block content %}
        
        {% endblock  %}
    </div>

    <footer class='py-6 px-6 flex justify-between bg-gray-800'>
        <div class='w-2/3 pr-10'>
            <h3 class='mb-5 font-semibold text-gray-400'>About</h3>
            <p class='text-lg text-gray-500'>Lorem Ipsum bla bla bla. Lorem Ipsum bla bla bla. Lorem Ipsum bla bla bla. Lorem Ipsum bla bla bla. </p>

        </div>
        <div class='w-1/3'>
            <h3 class='mb-5 font-semibold text-gray-400'>Menu</h3>

            <ul class='space-y-2'>
                <li><a href='#' class='text-lg text-teal-500 hover:text-teal-700'>About</a></li>
                <li><a href='https://fortune-akano.onrender.com/' target="_blank" class='text-lg text-teal-500 hover:text-teal-700'>Contact</a></li>
                <li><a href='#' class='text-lg text-teal-500 hover:text-teal-700'>Privacy Policy</a></li>
                <li><a href='#' class='text-lg text-teal-500 hover:text-teal-700'>Terms of Use</a></li>
            </ul>
        </div>

        <p class="text-x font-semibold text-center">Designed by <a class="font-bold" href='https://fortune-akano.onrender.com/' target="_blank">fortunecode</a></p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

  </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock  %}

{% block content %}

<div class= 'mt-6 px-6 py-12 bg-gray-100 rounded-xl'>
        <h2 class='mb-12 text-2xl text-center'>Newest items</h2>

        <div class='grid grid-cols-2 md:grid-cols-4 gap-1'>
            {% for item in items %}
                <div class="item">
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class='rounded-t-xl' width='75%' height='75%'>
                        </div>

                        <div class='p-6 bg-gray rounded-b-xl'>
                            <h2 class='text-2xl'>{{ item.name }}</h2>
                            <p class='text-gray-500'>Price: {{ item.price }}</p>
                            <a href="{% url 'cart:index' item.id %}" class='text-lg font-semibold hover:text-lime-900'>Add to cart</a>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class= 'mt-6 px-6 py-12 bg-gray-100 rounded-xl'>
        <h2 class='mb-12 text-2xl text-center'>Categories</h2>

        <div class='grid grid-cols-3 gap-3'>
            {% for category  in categories %}
                <div>
                    <a href='#'>

                        <div class='p-6 bg-gray rounded-b-xl'>
                            <h2 class='text-2xl'>{{ category.name }}</h2>
                            <p class='text-gray-500'>{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock  %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log In{% endblock title %}

{% block content %}
    <div class='w-1/2 p-6 my-6 mx-auto bg-gray-100 rounded-xl'>
        <h1 class='mb-6 text-3xl'>Log In</h1>

        <form method='POST' action='.'>
            {% csrf_token %}

            {{ form.non_field_errors }}

            <div class='mb-3'>
                <label class='inline-block mb-2'>Username</label><br>
                {{ form.username }}
            </div>

            

            <div class='mb-3'>
                <label class='inline-block mb-2'>Password</label><br>
                {{ form.password }}
            </div>

            

            {% if form.errors or form.non_field_errors %}
                <div class='mb-3 p-6bg-red-100 rounded-xl'>
                    {% for field in form  %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class='py-3 px-5 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white'>Login</button>
        </form>

    </div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign Up{% endblock title %}

{% block content %}
    <div class='w-1/2 p-6 my-6 mx-auto bg-gray-100 rounded-xl'>
        <h1 class='mb-6 text-3xl'>Sign Up</h1>

        <form method='POST' action='.'>
            {% csrf_token %}

            {{ form.non_field_errors }}

            <div class='mb-3'>
                <label class='inline-block mb-2'>Username</label><br>
                {{ form.username }}
            </div>

            <div class='mb-3'>
                <label class='inline-block mb-2'>Email</label><br>
                {{ form.email }}
            </div>

            <div class='mb-3'>
                <label class='inline-block mb-2'>Password</label><br>
                {{ form.password1 }}
            </div>

            <div class='mb-3'>
                <label class='inline-block mb-2'>Repeat Password</label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class='mb-3 p-6bg-red-100 rounded-xl'>
                    {% for field in form  %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class='py-3 px-5 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white'>Sign up</button>
        </form>

    </div>
{% endblock %}